### ISSUE TITLE
Automate the adjustment of the version

### ISSUE THREAD

**Issue by markusguenther** [FriendsOfReactJS/react-css-themr#36]
Currently the version number in the package.json is not updated automatically.
This is a bit sad because we have semantic-release that handles the tagging and npm publish.

**Describe alternatives you've considered**
We should script this problem away. So that the version number will be updated also in the package.json by semantic release. The git commit therefore will be done also automated then.

**Comment by rishichawda** [comment]
@markusguenther I'll be happy to take up this issue.

**Comment by markusguenther** [comment]
@rishichawda thank you ... I know already adjusted the config and now everything will be changed automatically :)
