### ISSUE TITLE
There is a serious bug about shouldComponentUpdate

### ISSUE THREAD

**Issue by ovaldi** [FriendsOfReactJS/react-css-themr#47]
```
@themr('tab', styles)
class Tab extends React.PureComponent {
   ... ...
   render () {
       <div className={ theme.tab } onClick={ this.props.onClick }>
         { this.props.children }
       </div>
    }
}
```

```
class Tabs extends React.Component {
  state = {
    text: 'blue'
  }

  handleClick = () => {
     this.setState({
       text: 'gray'
     });
  }

  render () {
     const { text } = this.state;

     return (
       <Tab onClick={ this.handleClick }>
         <Daily text={ text }/>
       </Tab>
     );
  }
}
```

When I trigger handleClick, the `Daily` will not update anything, because [shouldComponentUpdate](https://github.com/FriendsOfReactJS/react-css-themr/blob/61ba16d3d265ba7c5d82e909345e8e4a26dff71f/src/components/themr.js#L154) always return false in themr.js.
![image](https://user-images.githubusercontent.com/4537336/49062433-185ebc00-f24f-11e8-9eda-e21c02971cdb.png)

@markusguenther

**Comment by markusguenther** [comment]
Thanks for reporting this issue ... hope that I`ll find time for that asap. But it would be awesome to receive a PR ;)

**Comment by ovaldi** [comment]
@markusguenther  i have send a PR, Pls check it when you have time, thanks!
