### ISSUE TITLE
un-fork to allow search ability / discoverability

### ISSUE THREAD

**Issue by hartzis** [FriendsOfReactJS/react-css-themr#53]
**Is your enhancement request related to a problem? Please describe.**
Unable to find this package via github search.

**Describe the solution you'd like**
Suggest un-forking from [javivelasco/react-css-themr](https://github.com/javivelasco/react-css-themr) so it populates in github search results.

**Describe alternatives you've considered**
Suggest also adding more `package.json` keywords: `theme`, `css theme`, `react css theme` 🤷‍♀️
-  would help with npm search discoverability

**Additional context**
Thank you for picking this project up and carrying the banner of maintenance!

**Comment by markusguenther** [comment]
I am really thankful for your hints and the push to the independence 😜

I will try to make the changes soonish. Thanks @hartzis wish a happy new year and thanks for using the package

**Comment by markusguenther** [comment]
The package is now a standalone package. Only missing point is now a NPM release.
