### ISSUE TITLE
Latest props are not used in calculation of theme

### ISSUE THREAD

**Issue by GenoD** [FriendsOfReactJS/react-css-themr#78]
**Describe the bug**
When a new theme is passed to a themr wrapped component props, the old theme is still present.

**To Reproduce**
- Create a component that utilized react-css-themr. 
- Pass a custom theme needed to style child components
- Update them after initial render
- Notice old theme is still provided

**Expected behavior**
When theme is updated, recalculate with latest props

All platforms affected

**Comment by GenoD** [comment]
@markusguenther can you please view this issue and corresponding PR?

**Comment by markusguenther** [comment]
Hello,

I am sorry for the late reply. I am bit busy these days but will take a look soonish :)
Thanks for the contribution. I really appreciate that :)

**Comment by markusguenther** [comment]
Will release the new version later. It is already tagged but the semantic release tool made a mistake and not the tag number is wrong :(

Thanks for the contribution and hope to see you also in other commits :)
